global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: "litellm"
    metrics_path: /metrics
    static_configs:
      - targets: ["litellm:4000"]

  - job_name: continue_exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["continue-exporter:4010"]

  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
